server:
  port: 8081
  servlet:
    context-path: /crud

spring:
  application:
    name: crud
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3307/crud?allowPublicKeyRetrieval=true&sslMode=DISABLED&useSSL=false&ServerTimezone=UTC
    username: microservices
    password: microservices123
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

crud:
  rabbitmq:
    exchange: crud.exchange
    routing-key: crud.produto.routing-key

security:
  jwt:
    token:
      secret-key: 'p3s6v9y$B&E(H+MbQeThWmZq4t7w!z%C'